use crate::graph::{route_decorator, route_http_method, route_path, WikiGraph};
use std::collections::BTreeMap;

pub fn render_routes_page(graph: &WikiGraph) -> String {
    let mut md = String::new();
    md.push_str("---\ntitle: API Routes\nsidebar_position: 2\n---\n\n");
    md.push_str("# API Routes\n\n");

    if graph.routes.is_empty() {
        md.push_str("No routes found in the analyzed codebase.\n");
        return md;
    }

    md.push_str("| Method | Path | Handler | Decorator | File |\n");
    md.push_str("|---|---|---|---|---|\n");

    for (handler, route) in &graph.routes {
        let method = route_http_method(route);
        let path = route_path(route);
        let decorator = route_decorator(route);
        let handler_name = handler.qualified_name.as_deref().unwrap_or(&handler.name);
        let file = route.file.rsplit('/').next().unwrap_or(&route.file);
        md.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | `{}` |\n",
            method, path, handler_name, decorator, file
        ));
    }

    md
}

pub fn render_routes_json(graph: &WikiGraph) -> serde_json::Value {
    let mut paths: BTreeMap<String, BTreeMap<String, serde_json::Value>> = BTreeMap::new();

    for (handler, route) in &graph.routes {
        let method = route_http_method(route).to_lowercase();
        let path = route_path(route);
        let decorator = route_decorator(route);
        let handler_class = handler
            .qualified_name
            .as_deref()
            .unwrap_or(&handler.name)
            .split('#')
            .next()
            .unwrap_or(&handler.name)
            .to_string();

        let op_id = make_operation_id(&method, &path);
        let operation = serde_json::json!({
            "operationId": op_id,
            "summary": handler.name,
            "x-handler-id": handler.id.as_str(),
            "x-handler-class": handler_class,
            "x-decorator": decorator,
            "responses": { "200": { "description": "OK" } },
        });

        paths.entry(path).or_default().insert(method, operation);
    }

    let paths_val: serde_json::Value = paths
        .into_iter()
        .map(|(path, methods)| {
            (
                path,
                serde_json::Value::Object(methods.into_iter().collect::<serde_json::Map<_, _>>()),
            )
        })
        .collect::<serde_json::Map<_, _>>()
        .into();

    serde_json::json!({
        "openapi": "3.0.3",
        "info": {
            "title": "Indexed API Surface",
            "version": "1.0.0",
            "description": "Generated by cih-engine wiki. Schemas omitted."
        },
        "paths": paths_val,
    })
}

fn make_operation_id(method: &str, path: &str) -> String {
    let parts = path
        .split('/')
        .filter(|s| !s.is_empty())
        .map(|seg| {
            let seg = seg.trim_matches(|c| c == '{' || c == '}');
            seg.chars()
                .map(|c| if c.is_alphanumeric() { c } else { '_' })
                .collect::<String>()
        })
        .collect::<Vec<_>>()
        .join("_");
    let id = format!("{}_{}", method, parts);
    if id.len() > 64 {
        id[..64].to_string()
    } else {
        id
    }
}



