use std::collections::BTreeMap;
use crate::graph::{route_decorator, route_http_method, route_path, WikiGraph};

pub fn render_routes_page(graph: &WikiGraph) -> String {
    let mut md = String::new();
    md.push_str("---\nid: shared/routes\ntitle: API Routes\n---\n\n");
    md.push_str("# API Routes\n\n");

    if graph.routes.is_empty() {
        md.push_str("No routes found in the analyzed codebase.\n");
        return md;
    }

    md.push_str("| Method | Path | Handler | Decorator | File |\n");
    md.push_str("|---|---|---|---|---|\n");

    for (handler, route) in &graph.routes {
        let method = route_http_method(route);
        let path = route_path(route);
        let decorator = route_decorator(route);
        let handler_name = handler.qualified_name.as_deref().unwrap_or(&handler.name);
        let file = route.file.rsplit('/').next().unwrap_or(&route.file);
        md.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | `{}` |\n",
            method, path, handler_name, decorator, file
        ));
    }

    md
}

pub fn render_routes_json(graph: &WikiGraph) -> serde_json::Value {
    let mut paths: BTreeMap<String, BTreeMap<String, serde_json::Value>> = BTreeMap::new();

    for (handler, route) in &graph.routes {
        let method = route_http_method(route).to_lowercase();
        let path = route_path(route);
        let decorator = route_decorator(route);
        let handler_class = handler
            .qualified_name
            .as_deref()
            .unwrap_or(&handler.name)
            .split('#')
            .next()
            .unwrap_or(&handler.name)
            .to_string();

        let op_id = make_operation_id(&method, &path);
        let operation = serde_json::json!({
            "operationId": op_id,
            "summary": handler.name,
            "x-handler-id": handler.id.as_str(),
            "x-handler-class": handler_class,
            "x-decorator": decorator,
            "responses": { "200": { "description": "OK" } },
        });

        paths.entry(path).or_default().insert(method, operation);
    }

    let paths_val: serde_json::Value = paths
        .into_iter()
        .map(|(path, methods)| {
            (
                path,
                serde_json::Value::Object(
                    methods.into_iter().collect::<serde_json::Map<_, _>>(),
                ),
            )
        })
        .collect::<serde_json::Map<_, _>>()
        .into();

    serde_json::json!({
        "openapi": "3.0.3",
        "info": {
            "title": "Indexed API Surface",
            "version": "1.0.0",
            "description": "Generated by cih-engine wiki. Schemas omitted."
        },
        "paths": paths_val,
    })
}

fn make_operation_id(method: &str, path: &str) -> String {
    let parts = path
        .split('/')
        .filter(|s| !s.is_empty())
        .map(|seg| {
            let seg = seg.trim_matches(|c| c == '{' || c == '}');
            seg.chars()
                .map(|c| if c.is_alphanumeric() { c } else { '_' })
                .collect::<String>()
        })
        .collect::<Vec<_>>()
        .join("_");
    let id = format!("{}_{}", method, parts);
    if id.len() > 64 {
        id[..64].to_string()
    } else {
        id
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use cih_core::{Edge, EdgeKind, Node, NodeId, NodeKind, Range};

    fn route_pair(method: &str, path: &str, handler_id: &str) -> (Node, Node) {
        let handler = Node {
            id: NodeId::new(handler_id.to_string()),
            kind: NodeKind::Method,
            name: handler_id.split('#').nth(1).unwrap_or("handle").to_string(),
            qualified_name: Some(handler_id.to_string()),
            file: "Controller.java".to_string(),
            range: Range::default(),
            props: None,
        };
        let route_name = format!("{} {}", method, path);
        let route = Node {
            id: NodeId::new(format!("Route:{}", route_name)),
            kind: NodeKind::Route,
            name: route_name,
            qualified_name: None,
            file: "Controller.java".to_string(),
            range: Range::default(),
            props: Some(serde_json::json!({
                "httpMethod": method,
                "path": path,
                "decorator": format!("{}Mapping", &method[..1]),
            })),
        };
        (handler, route)
    }

    fn graph_with_routes(pairs: Vec<(Node, Node)>) -> WikiGraph {
        let mut nodes: Vec<Node> = Vec::new();
        let mut edges: Vec<Edge> = Vec::new();
        for (handler, route) in pairs {
            edges.push(Edge {
                src: handler.id.clone(),
                dst: route.id.clone(),
                kind: EdgeKind::HandlesRoute,
                confidence: 1.0,
                reason: String::new(),
            });
            nodes.push(handler);
            nodes.push(route);
        }
        WikiGraph::build(&nodes, &edges, &[], &[])
    }

    #[test]
    fn render_routes_page_produces_table() {
        let (h, r) = route_pair("GET", "/api/orders", "com.example.OrderController#list/0");
        let g = graph_with_routes(vec![(h, r)]);
        let md = render_routes_page(&g);
        assert!(md.contains("---\nid: shared/routes"), "has frontmatter");
        assert!(md.contains("| Method |"), "has table header");
        assert!(md.contains("/api/orders"), "has path");
        assert!(md.contains("`GET`"), "has method");
    }

    #[test]
    fn render_routes_json_is_openapi() {
        let (h, r) = route_pair("POST", "/api/orders", "com.example.OrderController#create/0");
        let g = graph_with_routes(vec![(h, r)]);
        let val = render_routes_json(&g);
        assert_eq!(val["openapi"], "3.0.3");
        assert!(val["paths"]["/api/orders"]["post"].is_object());
    }

    #[test]
    fn markdown_pages_include_docusaurus_frontmatter() {
        let (h, r) = route_pair("GET", "/api/health", "com.example.HealthController#check/0");
        let g = graph_with_routes(vec![(h, r)]);
        let md = render_routes_page(&g);
        assert!(md.starts_with("---\n"), "page must start with frontmatter delimiter");
        assert!(md.contains("id:"), "frontmatter must contain id");
        assert!(md.contains("title:"), "frontmatter must contain title");
    }
}
