// @ts-check
const path = require('path');
const { themes: prismThemes } = require('prism-react-renderer');

// Point at any repo's wiki output: CIH_WIKI_PATH=/path/to/repo/.cih/wiki/pages npm start
const wikiPath = process.env.CIH_WIKI_PATH
  ? path.resolve(process.env.CIH_WIKI_PATH)
  : path.resolve(__dirname, 'docs');

// Auto-read repo name from manifest.json if present, otherwise fall back to env var or basename
let repoName = process.env.CIH_REPO_NAME || path.basename(path.dirname(path.dirname(wikiPath)));
try {
  const manifest = require(path.join(wikiPath, '..', 'manifest.json'));
  if (manifest.repo_name) repoName = manifest.repo_name;
} catch {}

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: `${repoName} — CIH Docs`,
  tagline: 'Code Intelligence Hub — Role-Based Documentation',
  favicon: undefined,
  url: 'http://localhost',
  baseUrl: '/',
  onBrokenLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  // Treat .md files as CommonMark — avoids JSX parse errors from generic
  // type signatures like ResponseEntity<PaymentReceipt> in table cells.
  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          path: wikiPath,
          routeBasePath: '/',
          sidebarPath: require.resolve('./sidebars.js'),
          exclude: ['**/*.json'],
          editUrl: undefined,
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: repoName,
        items: [],
      },
      footer: {
        style: 'dark',
        copyright: 'Generated by Code Intelligence Hub (yummy-cih)',
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ['java', 'bash', 'json'],
      },
      colorMode: {
        defaultMode: 'light',
        disableSwitch: false,
      },
    }),
};

module.exports = config;
