// @ts-check
'use strict';

const path = require('path');
const fs = require('fs');
const { themes: prismThemes } = require('prism-react-renderer');

// Single-repo: set CIH_WIKI_PATH=/path/to/.cih/wiki/pages
// Multi-repo:  set CIH_WIKI_REPOS_DIR=/wiki (each subdir = one repo)
const singlePath = process.env.CIH_WIKI_PATH
  ? path.resolve(process.env.CIH_WIKI_PATH)
  : null;
const reposDir = process.env.CIH_WIKI_REPOS_DIR
  ? path.resolve(process.env.CIH_WIKI_REPOS_DIR)
  : '/wiki';
const multiMode = !singlePath;

function readRepoName(pagesDir) {
  try {
    const m = JSON.parse(fs.readFileSync(path.join(pagesDir, '..', 'manifest.json'), 'utf-8'));
    if (m.repo_name) return m.repo_name;
  } catch {}
  return process.env.CIH_REPO_NAME || path.basename(path.dirname(path.dirname(pagesDir)));
}

function listRepoDirs(dir) {
  try {
    return fs.readdirSync(dir)
      .filter(f => {
        try { return fs.statSync(path.join(dir, f)).isDirectory(); } catch { return false; }
      })
      .sort();
  } catch {
    return [];
  }
}

const repoDirs = multiMode ? listRepoDirs(reposDir) : [];
const siteTitle = multiMode
  ? 'CIH Docs'
  : `${readRepoName(singlePath)} — CIH Docs`;

const singleDocsConfig = {
  path: singlePath,
  routeBasePath: '/docs',
  sidebarPath: require.resolve('./sidebars.js'),
  exclude: ['**/*.json'],
  editUrl: undefined,
};

// One plugin-content-docs instance per repo in multi-repo mode.
// The preset-classic docs plugin is disabled in that mode.
const repoPlugins = repoDirs.map(slug => [
  '@docusaurus/plugin-content-docs',
  {
    id: slug,
    path: path.join(reposDir, slug),
    routeBasePath: `/${slug}`,
    sidebarPath: require.resolve('./sidebars.js'),
    exclude: ['**/*.json'],
    editUrl: undefined,
  },
]);

const navItems = multiMode
  ? repoDirs.map(slug => ({ label: slug, to: `/${slug}/`, position: 'left' }))
  : [];

/** @type {import('@docusaurus/types').Config} */
module.exports = {
  title: siteTitle,
  tagline: 'Code Intelligence Hub — Role-Based Documentation',
  favicon: undefined,
  url: 'http://localhost',
  baseUrl: '/',
  onBrokenLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    mermaid: true,
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  themes: [
    '@docusaurus/theme-mermaid',
    // Offline navbar search — the fallback when the landing page's live
    // /wiki/search (cih-server) is unreachable.
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: multiMode ? repoDirs.map(slug => `/${slug}`) : '/docs',
        docsDir: multiMode ? repoDirs.map(slug => path.join(reposDir, slug)) : [singlePath],
      },
    ],
  ],
  plugins: repoPlugins,

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: multiMode ? false : singleDocsConfig,
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: siteTitle,
        items: navItems,
      },
      footer: {
        style: 'dark',
        copyright: 'Generated by Code Intelligence Hub (yummy-cih)',
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ['java', 'bash', 'json'],
      },
      tableOfContents: {
        minHeadingLevel: 2,
        maxHeadingLevel: 4,
      },
      colorMode: {
        defaultMode: 'light',
        disableSwitch: false,
      },
    }),
};
