// @ts-check
'use strict';

const path = require('path');
const fs = require('fs');
const { themes: prismThemes } = require('prism-react-renderer');

// ── Mode detection ────────────────────────────────────────────────────────────
// Single-repo: set CIH_WIKI_PATH=/path/to/.cih/wiki/pages
// Multi-repo:  set CIH_WIKI_REPOS_DIR=/wiki (each subdir = one repo)
const singlePath = process.env.CIH_WIKI_PATH
  ? path.resolve(process.env.CIH_WIKI_PATH)
  : null;
const reposDir = process.env.CIH_WIKI_REPOS_DIR
  ? path.resolve(process.env.CIH_WIKI_REPOS_DIR)
  : '/wiki';
const multiMode = !singlePath;

// ── Helpers ───────────────────────────────────────────────────────────────────
function readRepoName(pagesDir) {
  try {
    const m = JSON.parse(fs.readFileSync(path.join(pagesDir, '..', 'manifest.json'), 'utf-8'));
    if (m.repo_name) return m.repo_name;
  } catch {}
  return process.env.CIH_REPO_NAME || path.basename(path.dirname(path.dirname(pagesDir)));
}

function listRepoDirs(dir) {
  try {
    return fs.readdirSync(dir)
      .filter(f => { try { return fs.statSync(path.join(dir, f)).isDirectory(); } catch { return false; } })
      .sort();
  } catch { return []; }
}

// ── Resolve repos ─────────────────────────────────────────────────────────────
const repoDirs = multiMode ? listRepoDirs(reposDir) : [];

// One @docusaurus/plugin-content-docs instance per repo in multi-repo mode.
// The preset-classic docs plugin is disabled in this mode.
const repoPlugins = repoDirs.map(slug => [
  '@docusaurus/plugin-content-docs',
  {
    id: slug,
    path: path.join(reposDir, slug),
    routeBasePath: `/${slug}`,
    sidebarPath: require.resolve('./sidebars.js'),
    exclude: ['**/*.json'],
    editUrl: undefined,
  },
]);

// Navbar links in multi-repo mode: one item per repo
const navItems = multiMode
  ? repoDirs.map(slug => ({ label: slug, to: `/${slug}/`, position: 'left' }))
  : [];

const siteTitle = multiMode
  ? 'CIH Docs'
  : `${readRepoName(singlePath)} — CIH Docs`;

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: siteTitle,
  tagline: 'Code Intelligence Hub — Role-Based Documentation',
  favicon: undefined,
  url: 'http://localhost',
  baseUrl: '/',
  onBrokenLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  plugins: repoPlugins,

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: multiMode
          ? false  // disabled — each repo is its own plugin
          : {
              path: singlePath,
              routeBasePath: '/',
              sidebarPath: require.resolve('./sidebars.js'),
              exclude: ['**/*.json'],
              editUrl: undefined,
            },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: siteTitle,
        items: navItems,
      },
      footer: {
        style: 'dark',
        copyright: 'Generated by Code Intelligence Hub (yummy-cih)',
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ['java', 'bash', 'json'],
      },
      colorMode: {
        defaultMode: 'light',
        disableSwitch: false,
      },
    }),
};

module.exports = config;
