//! DDL for the strict LadybugDB schema. Mirrors the Falkor adapter's storage
//! model: one wide `Symbol` node table (single label, `kind` as a property
//! column, the 19 flattened columns + the dynamic `props` JSON string), and
//! one rel table per `EdgeKind` — real rel tables are required for the typed
//! and multi-label recursive patterns (`[:CALLS|:HANDLES_ROUTE*1..n]`), and
//! each gets its own CSR adjacency.

use cih_core::EdgeKind;
use cih_graph_store::{GraphStoreError, Result};
use lbug::Connection;
use strum::IntoEnumIterator;

/// Column order here is the contract for `bulk.rs`'s CSV writer — keep in sync.
pub(crate) const SYMBOL_DDL: &str = "CREATE NODE TABLE IF NOT EXISTS Symbol(
    id STRING PRIMARY KEY, name STRING, kind STRING, file STRING, qn STRING,
    sl INT64, el INT64, props STRING, stereotype STRING, httpMethod STRING,
    path STRING, decorator STRING, handler STRING, symbolCount INT64,
    cohesion DOUBLE, processType STRING, cyclomatic INT64, cognitive INT64,
    loopDepth INT64, transitiveLoopDepth INT64)";

pub(crate) const NODE_COLUMNS: [&str; 20] = [
    "id",
    "name",
    "kind",
    "file",
    "qn",
    "sl",
    "el",
    "props",
    "stereotype",
    "httpMethod",
    "path",
    "decorator",
    "handler",
    "symbolCount",
    "cohesion",
    "processType",
    "cyclomatic",
    "cognitive",
    "loopDepth",
    "transitiveLoopDepth",
];

pub(crate) const EDGE_COLUMNS: [&str; 5] = ["src", "dst", "confidence", "reason", "callSites"];

/// One `CREATE REL TABLE` per `EdgeKind`, generated by iteration so a new
/// kind can't be forgotten (`Other` maps to `REL` like everywhere else).
pub(crate) fn rel_table_ddls() -> Vec<String> {
    EdgeKind::iter()
        .map(|kind| {
            format!(
                "CREATE REL TABLE IF NOT EXISTS {}(FROM Symbol TO Symbol, \
                 confidence DOUBLE, reason STRING, callSites STRING)",
                kind.cypher_label()
            )
        })
        .collect()
}

pub(crate) fn apply_schema(conn: &Connection) -> Result<()> {
    conn.query(SYMBOL_DDL)
        .map_err(|e| GraphStoreError::Backend(format!("create Symbol table: {e}")))?;
    for ddl in rel_table_ddls() {
        conn.query(&ddl)
            .map_err(|e| GraphStoreError::Backend(format!("create rel table: {e}")))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn one_rel_table_per_edge_kind_and_other_is_rel() {
        let ddls = rel_table_ddls();
        assert_eq!(ddls.len(), EdgeKind::iter().count());
        assert!(ddls.iter().any(|d| d.contains(" REL(")), "Other → REL");
        assert!(ddls.iter().any(|d| d.contains(" CALLS(")));
    }
}
