//! Documentation-evidence MCP adapters (`doc_pack`, `doc_status`).

use rmcp::handler::server::wrapper::Parameters;
use rmcp::{model::CallToolResult, tool, tool_router, ErrorData as McpError};

use super::super::error::{app_error_to_mcp, json_result};
use super::super::CihServer;
use crate::application::doc_pack::{DocPackCommand, DocStatusCommand};
use crate::transport::mcp::args::{DocPackArgs, DocStatusArgs};

#[tool_router(router = doc_pack_router, vis = "pub(crate)")]
impl CihServer {
    #[tool(
        description = "Return a curated, bounded documentation evidence pack for one node \
            (Route, Method, Function, Constructor, Class, or Interface): identity, execution \
            flow with DB effects, callers/processes, tests, a source excerpt, and (for routes \
            in a group) cross-repo consumers — plus a deterministic markdown skeleton with \
            frontmatter carrying an evidence hash and the exact delivered profile. Write \
            prose only from this delivered evidence; every section reports explicit \
            completeness. Regenerate stale pages using the frontmatter's \
            cih_requested_profile; doc_status(docs_dir=...) lists which pages are stale."
    )]
    async fn doc_pack(
        &self,
        Parameters(args): Parameters<DocPackArgs>,
    ) -> Result<CallToolResult, McpError> {
        let command = DocPackCommand::try_new(
            args.name,
            args.repo,
            args.group,
            args.include_source,
            args.sections,
        )
        .map_err(app_error_to_mcp)?;
        let output = self
            .doc_pack_service()
            .execute(command)
            .await
            .map_err(app_error_to_mcp)?;
        json_result(&output)
    }

    #[tool(
        description = "Scan a repo-relative docs directory for pages generated by doc_pack \
            (frontmatter cih_* keys) and report each page's freshness: fresh, stale, \
            missing_node, unparseable, or error. Rebuilds each page's evidence hash under \
            its stored profile — only node-local evidence changes mark a page stale; \
            unrelated repository changes do not. Regenerate stale pages with doc_pack, \
            preserving prose between the cih:prose markers."
    )]
    async fn doc_status(
        &self,
        Parameters(args): Parameters<DocStatusArgs>,
    ) -> Result<CallToolResult, McpError> {
        let command = DocStatusCommand::try_new(args.repo, args.docs_dir, args.max_pages)
            .map_err(app_error_to_mcp)?;
        let output = self
            .doc_pack_service()
            .status(command)
            .await
            .map_err(app_error_to_mcp)?;
        json_result(&output)
    }
}
